"""empty message

Revision ID: 164c1f2bb037
Revises:
Create Date: 2026-09-05 17:49:35.540479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164c1f2bb037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifier_mapping_migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_index_data', sa.BigInteger(), nullable=False),
    sa.Column('new_index_data', sa.BigInteger(), nullable=False),
    sa.Column('migration_id', sa.String(), nullable=True),
    sa.Column('applied', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_index_data', 'new_index_data', name='unique_index_data_pair')
    )
    op.create_index(op.f('ix_identifier_mapping_migrations_new_index_data'), 'identifier_mapping_migrations', ['new_index_data'], unique=False)
    op.create_index(op.f('ix_identifier_mapping_migrations_old_index_data'), 'identifier_mapping_migrations', ['old_index_data'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identifier_mappings',
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_schema', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('route_method', sa.String(), nullable=False),
    sa.Column('route_path', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('index_data', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identifier_mappings_index_data'), 'identifier_mappings', ['index_data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identifier_mappings_index_data'), table_name='identifier_mappings')
    op.drop_table('identifier_mappings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_identifier_mapping_migrations_old_index_data'), table_name='identifier_mapping_migrations')
    op.drop_index(op.f('ix_identifier_mapping_migrations_new_index_data'), table_name='identifier_mapping_migrations')
    op.drop_table('identifier_mapping_migrations')
    # ### end Alembic commands ###
